# Generated by Django 3.1.4 on 2021-01-01 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0003_auto_20201219_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default='', max_length=200, verbose_name='Логин')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО учащегося')),
                ('date', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('parents', models.CharField(max_length=200, verbose_name='Родители')),
                ('number', models.CharField(blank=True, max_length=11, verbose_name='Телефон родителей')),
                ('url_for_mess', models.SlugField(default='', max_length=200)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Группа', to='loginsys.groups')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='teacher', max_length=200, verbose_name='Статус')),
                ('login', models.CharField(default='', max_length=200, verbose_name='Логин')),
                ('password', models.CharField(default='', max_length=200, verbose_name='Пароль')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО преподавателя')),
                ('position', models.CharField(max_length=200, verbose_name='Должность преподавателя')),
                ('number', models.CharField(blank=True, max_length=11, verbose_name='Контактный телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('education', models.CharField(max_length=200, verbose_name='Образование')),
                ('degree', models.CharField(blank=True, max_length=11, verbose_name='Ученая степень')),
                ('date_b', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('date_j', models.DateField(blank=True, verbose_name='Дата трудоустройства')),
                ('url_for_mess', models.SlugField(default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
