# Generated by Django 3.1.4 on 2021-01-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginsys', '0006_remove_groups_slug'),
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Lecture',
        ),
    ]
