# Generated by Django 3.1.7 on 2021-03-20 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_auto_20210111_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'verbose_name': 'Лекция', 'verbose_name_plural': 'Лекции'},
        ),
    ]
