# Generated by Django 3.1.4 on 2020-12-18 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_user', models.CharField(choices=[('1', 'Директор'), ('2', 'Преподаватель'), ('3', 'Студент')], default='1', max_length=2, verbose_name='Выбор получателя')),
                ('text', models.TextField(max_length=500, verbose_name='Сообщение')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата отправки')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='От кого')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
